---
title: Tim Durrant
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: tim.j.durrant@gmail.com
description: 
baseurl: ''
url: https://timdurrant.com
twitter_username: tim_durrant
facebook_username: timjohndurrant
instagram_username: 
github_username: tim-durrant
linkedin_username: timdurrant
telegram_username: tim_durrant
name: Tim Durrant
blurb: Dad, DIYer, Mac convert [Blogger, author & web dev]
markdown: kramdown
host: sites.timdurrant.com
